#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubygems'

lib_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH << lib_dir unless $LOAD_PATH.include?(lib_dir)

if File.exist?('.env.development')
  # This loads our development environment when running dev.
  require 'dotenv'
  Dotenv.load('.env.development')
end

require 'dsu'

if Dsu.env.development?
  # This simply allows us to use a folder other than dsu folder for the production
  # release, so we don't mess with our current production dsu folder.
  module Dsu
    module Support
      module Fileable
        def root_folder
          File.join(gem_dir, '.development_home')
        end
      end
    end
  end
end

Dsu::CLI.start
