#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubygems'

lib_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH << lib_dir unless $LOAD_PATH.include?(lib_dir)

require 'dsu'

Dsu::CLI.start
