name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.0.7', '3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@v3
      - name: Set timezone on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo timedatectl set-timezone 'America/New_York'

      - name: Set timezone on macOS
        if: matrix.os == 'macos-latest'
        run: sudo systemsetup -settimezone America/New_York

      - name: Set timezone on Windows
        if: matrix.os == 'windows-latest'
        run: tzutil /s "Eastern Standard Time"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Update RubyGems
        run: gem update --system

      - name: Disable bundler frozen setting
        run: bundle config set frozen false

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
